#!/bin/bash

if [ $# -ne 1 ]; then
	echo "Usage: sphp [phpversion]"
	exit 1
fi

currentversion="`php -r \"echo str_replace('.', '', substr(phpversion(), 0, 3));\"`"
newversion="`echo $1 | sed -e 's/php//g'`"

brew list php$newversion 2> /dev/null > /dev/null

if [ $? -eq 0 ]; then
	echo "PHP version $newversion found"

	echo "Stopping nginx"
	sudo launchctl unload /Library/LaunchDaemons/homebrew.mxcl.nginx.plist

	echo "Stopping PHP $currentversion"
	brew services stop php$currentversion

	echo "Unlinking old binaries..."
	brew unlink php$currentversion 2> /dev/null > /dev/null

	echo "Linking new binaries..."
	brew link php$newversion

	echo "Starting PHP $newversion"
	brew services start php$newversion

	echo "Starting nginx"
	sudo launchctl load /Library/LaunchDaemons/homebrew.mxcl.nginx.plist

	echo "Done."
else
	echo "PHP version $newversion was not found."
	exit 1
fi
